database {
  dataSourceClassName = "io.rqlite.rqlite4j.RqliteDataSource"
  dataSourceClassName = ${?DB_DRIVER}
  dataSource {
    url = "jdbc:rqlite:http://localhost:4001"
    url = ${?DB_URL}
  }
}

server {
  host = "0.0.0.0"
  host = ${?SERVER_HOST}
  port = 8080
  port = ${?SERVER_PORT}
  # Dev mode: serve static assets from filesystem
  # In production, a reverse proxy (nginx) serves static files
  dev-mode = true
  dev-mode = ${?SERVER_DEV_MODE}
}
